name: Build SuperClipboard

on: [push]

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

  strategy:
    fail-fast: false
    matrix:
      os: [windows-latest, macos-latest, ubuntu-latest]

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
    - run: npm install
    - run: npm run package
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Cleanup Artifacts for Windows
      if: matrix.os == 'windows-latest'
    - run: |
        npx rimraf "release/build/!(*.exe)"

    - name: Cleanup Artifacts for MacOS
      if: matrix.os == 'macos-latest'
    - run: |
        npx rimraf "release/build/!(*.dmg)"

    - name: upload artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: release/build

    - name: release
    - uses: softprops/action-gh-release@v0.1.16
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
