name: SuperClipboard
push:
  tags:
    - 'v*'
jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: publish
        run: npm run package
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "release/build/!(*.dmg)"

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SuperClipboard-macos
          path: release/build/*.dmg

  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: publish
        run: npm run package-win
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "release/build/!(*.exe)"

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SuperClipboard-windows
          path: release/build/*.exe
